import Head from 'next/head'
import Body from '../components/Body'
import WorkingOnIt from '../components/WorkingOnIt'
import PageTitle from '../components/PageTitle'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Body >
                <PageTitle title={"Balance"} link={"/balance"} />
                <WorkingOnIt />
            </Body>
        </div>
    )
}
