import { Alert } from "@mantine/core";
import Head from "next/head";
import Body from "../components/Body";
import CardList from "../components/CardList";
// import Alert from "../components/shared/Alert";
import Table from "../components/Table";

export default function DashboardPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body
        alert={
          <Alert
            withCloseButton
            closeButtonLabel="Close alert"
            title="Bummer!"
            color="red"
            className="rounded-md"
          >
            Something terrible happened! You made a mistake and there is no
            going back, your data was lost forever!
          </Alert>
        }
      >
        <CardList />
        {/* <Dashboard /> */}
        <Table title={"Recent Transactions"} />
      </Body>
    </div>
  );
}
