import Head from "next/head";
import Body from "../components/Body";
import CardList from "../components/CardList";
import Dashboard from "../components/Dashboard";
import Table from "../components/Table";

export default function DashboardPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <CardList />
        {/* <Dashboard /> */}
        <Table title={"Recent Transactions"} />
      </Body>
    </div>
  );
}
