import Head from 'next/head';
import { Navbar, IndexBody } from '../components/IndexPage'

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='font-notosans'>
        <Navbar />
        <IndexBody />
      </div>
    </div>
  )
}

export default Home;