import Head from "next/head";
import Login from "../components/Login";

function LoginPage() {
  return (
    <div>
      <Head>
        <title>Expense Tracker | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-roboto">
        <Login />
      </div>
    </div>
  );
}

export default LoginPage;
